services:
  postgres:
    container_name: postgres_container
    image: postgres:15
    ports:
      - "5432:5432"  # Cambia a "5433:5432" si el puerto 5432 está ocupado
    environment:
      POSTGRES_DB: practica_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: